/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentEarth: typeof import('./components/Earth/ComponentEarth.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTag: typeof import('element-plus/es')['ElTag']
    FrameWork: typeof import('./components/frameWork/index.vue')['default']
    Gitee: typeof import('./components/giteeIcon/gitee.vue')['default']
    Github: typeof import('./components/githubIcon/github.vue')['default']
    HeroBackground: typeof import('./components/heroBackground/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgBlue: typeof import('./components/svg-element/SvgBlue.vue')['default']
    SvgInputs: typeof import('./components/svg-element/SvgInputs.vue')['default']
    SvgNodes: typeof import('./components/svg-element/SvgNodes.vue')['default']
    SvgOutputs: typeof import('./components/svg-element/SvgOutputs.vue')['default']
  }
}
